### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'data'

### ISSUE THREAD

**Issue by dylanthomas** [ikostrikov/pytorch-a3c#10]
when I ran your code, it spitted out the following:

..
[2017-03-17 20:15:21,067] Making new env: PongDeterministic-v3
[2017-03-17 20:15:21,075] Making new env: PongDeterministic-v3
Process Process-3:
Traceback (most recent call last):
  File "/home/john/anaconda3/envs/th/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/john/anaconda3/envs/th/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/john/dev/pytorch-a3c/train.py", line 24, in train
    shared_param.grad.data = param.grad.data
AttributeError: 'NoneType' object has no attribute 'data'
Process Process-8:
...
...
  File "/home/john/dev/pytorch-a3c/train.py", line 24, in train
    shared_param.grad.data = param.grad.data
AttributeError: 'NoneType' object has no attribute 'data'
Time 00h 00m 01s, episode reward -21.0, episode length 764
...

1.
In the end it looks like it's running.  Am I right?

2.
Then, what is the cause the error messages ?

Many thanks !

(I am running this in conda env with python 3.5)

**Comment by ikostrikov** [comment]
We have already fixed this problem. Pull recent code from the repo.
