### ISSUE TITLE
big bug

### ISSUE THREAD

**Issue by harini20** [ikostrikov/pytorch-a3c#57]
I encountered an error
[INFO ] [Logger ] Record log in C:\Users\ArunD\.kivy\logs\kivy_18-09-24_3.txt
[INFO ] [Kivy ] v1.10.1.dev0, git-484b2f7, 20170513
[INFO ] [Python ] v3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
[INFO ] [Factory ] 194 symbols loaded
[INFO ] [Image ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO ] [Text ] Provider: sdl2
[INFO ] [OSC ] using <thread> for socket
[INFO ] [Window ] Provider: sdl2
[INFO ] [GL ] Using the "OpenGL" graphics system
[INFO ] [GL ] GLEW initialization succeeded
[INFO ] [GL ] Backend used <glew>
[INFO ] [GL ] OpenGL version <b'4.4.0 - Build 20.19.15.4835'>
[INFO ] [GL ] OpenGL vendor <b'Intel'>
[INFO ] [GL ] OpenGL renderer <b'Intel(R) HD Graphics'>
[INFO ] [GL ] OpenGL parsed version: 4, 4
[INFO ] [GL ] Shading version <b'4.40 - Build 20.19.15.4835'>
[INFO ] [GL ] Texture max size <16384>
[INFO ] [GL ] Texture max units <32>
[INFO ] [Shader ] fragment shader: <b"WARNING: 0:7: '' : #version directive missing">
[INFO ] [Shader ] vertex shader: <b"WARNING: 0:7: '' : #version directive missing">
[INFO ] [Window ] auto add sdl2 input provider
[INFO ] [Window ] virtual keyboard not allowed, single mode, not docked
[INFO ] [Base ] Start application main loop
C:\Users\ArunD\Documents\self-driving car\Self_Driving_Car\ai.py:63: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
probs = F.softmax(self.model(Variable(state, volatile = True))*100) # T=100
C:\Users\ArunD\Documents\self-driving car\Self_Driving_Car\ai.py:63: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
probs = F.softmax(self.model(Variable(state, volatile = True))*100) # T=100
[INFO ] [Base ] Leaving application in progress...
Traceback (most recent call last):
File "map.py", line 235, in <module>
CarApp().run()
File "C:\Users\ArunD\Anaconda3\lib\site-packages\kivy\app.py", line 828, in run
runTouchApp()
File "C:\Users\ArunD\Anaconda3\lib\site-packages\kivy\base.py", line 504, in runTouchApp
EventLoop.window.mainloop()
File "C:\Users\ArunD\Anaconda3\lib\site-packages\kivy\core\window\window_sdl2.py", line 663, in mainloop
self._mainloop()
File "C:\Users\ArunD\Anaconda3\lib\site-packages\kivy\core\window\window_sdl2.py", line 405, in _mainloop
EventLoop.idle()
File "C:\Users\ArunD\Anaconda3\lib\site-packages\kivy\base.py", line 339, in idle
Clock.tick()
File "C:\Users\ArunD\Anaconda3\lib\site-packages\kivy\clock.py", line 581, in tick
self._process_events()
File "kivy\_clock.pyx", line 367, in kivy._clock.CyClockBase._process_events (kivy\_clock.c:7700)
File "kivy\_clock.pyx", line 397, in kivy._clock.CyClockBase._process_events (kivy\_clock.c:7577)
File "kivy\_clock.pyx", line 395, in kivy._clock.CyClockBase._process_events (kivy\_clock.c:7498)
File "kivy\_clock.pyx", line 167, in kivy._clock.ClockEvent.tick (kivy\_clock.c:3490)
File "map.py", line 131, in update
action = brain.update(last_reward, last_signal)
File "C:\Users\ArunD\Documents\self-driving car\Self_Driving_Car\ai.py", line 79, in update
action = self.select_action(new_state)
File "C:\Users\ArunD\Documents\self-driving car\Self_Driving_Car\ai.py", line 64, in select_action
action = probs.multinomial()
TypeError: multinomial() missing 1 required positional arguments: "num_samples"

**Comment by ikostrikov** [comment]
The problem has been fixed in one of the recent commit.
